name: Build Linux Binaries

on:
  push:
    branches:
      - main
  pull_request:
  tags:
    - 'v*'
  workflow_dispatch:

jobs:
  Blint-GNU-Build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-22.04
            binary_name: blint-linux-amd64
          - os: ubuntu-22.04-arm
            binary_name: blint-linux-arm64
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
    - uses: actions/checkout@v4
      with:
        path: blint
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Linux packages
      run: |
        sudo apt-get update
        sudo apt-get install zlib1g-dev libzstd-dev llvm-18 llvm-18-dev
    - name: Install poetry
      id: poetry
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install setuptools pyinstaller poetry
        cd blint
        poetry config virtualenvs.create false
        poetry install --all-groups --all-extras --no-cache
      env:
        NYXSTONE_LLVM_PREFIX: /usr/lib/llvm-18
    - name: Binary gnu build
      run: |
        cd blint
        pyinstaller blint/cli.py --noconfirm --log-level=WARN \
          --nowindow \
          --onefile \
          --name ${{ matrix.binary_name }} \
          --add-data="blint/data:blint/data" \
          --add-data="blint/data/annotations:blint/data/annotations" \
          --collect-submodules blint \
          --collect-submodules multi-demangle \
          --collect-submodules oras \
          --noupx
        ./dist/${{ matrix.binary_name }} -i dist/${{ matrix.binary_name }} -o /tmp/reports
        sha256sum ./dist/${{ matrix.binary_name }} > ./dist/${{ matrix.binary_name }}.sha256
      env:
        PYTHONIOENCODING: utf-8
        LANG: en_US.utf-8
    - uses: actions/upload-artifact@v4
      with:
        path: ./blint/dist
        name: ${{ matrix.binary_name }}
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          blint/dist/${{ matrix.binary_name }}
          blint/dist/${{ matrix.binary_name }}.sha256    
