name: Build Windows Binaries

on:
  push:
  workflow_dispatch:

jobs:
  Blint-Build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        path: blint
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install poetry
      id: poetry
      run: |
        python -m pip install twine setuptools wheel poetry
        cd blint
        python -m poetry install

    - name: Binary windows build
      run: |
        cd blint
        python -m poetry run pyinstaller blint/cli.py --noconfirm --log-level=WARN --nowindow --onefile --name blint --collect-all blint --disable-windowed-traceback -i blint.ico --version-file=file_version_info.txt 
        set PYTHONIOENCODING=UTF-8
        .\dist\blint.exe -i .\dist\blint.exe -o reports --no-banner
      env:
        PYTHONIOENCODING: utf-8
        LANG: en_US.utf-8
    - uses: actions/upload-artifact@v1
      with:
        path: blint/dist
        name: blint-windows
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          blint/dist/blint.exe
